workflows:
  Libre-workflow:
    name: Libry pipline
    scripts:
      - name: Install CocoaPods dependencies
            script: |
                  pod install
      - name: CICD started
        script:  echo "setup done"
      - name: Build Libre
        script: xcodebuild build -workspace "Libre.xcworkspace" -scheme "Libre" CODE_SIGN_INDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    publishing:
        email:
           recipients:
               - faizulkarim28@gmail.com
    artifacts:
            - /tmp/xcodebuild_logs/*.log
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM